resources:
  - name: dbp_repooo
    type: GitRepo
    configuration:
      gitProvider: zen1                       # <-- replace with your integration
      path: aaragorn2/dbp    # <-- replace with your repository name
      branches:
        include: master
 
  - name: dbp_imageee	
    type: Image	
    configuration:	
      registry: zen_art	
      sourceRepository: docker_local	
      imageName: pipelines.westus.cloudapp.azure.com:8082/docker-local/mydockerbase	
      imageTag: latest	
      autoPull: true 
      
  - name: dbp_build_infooo
    type: BuildInfo
    configuration:
      sourceArtifactory: zen_art
      buildName: dbp_build
      buildNumber: 1    

  - name: dbp_promoted_build_info
    type: BuildInfo
    configuration:
      sourceArtifactory: zen_art
      buildName: dbp_build
      buildNumber: 1
 
  # Release bundle
  - name: release_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDist
      name: demo_rb
      version: v1.0.0
 
  # Signed version of the same release bundle
  - name: signed_bundle
    type: ReleaseBundle
    configuration:
      sourceDistribution: myDist
      name: demo_rb
      version: v1.0.0
 
  # Distribution rules
  - name: distribution_rules
    type: DistributionRule
    configuration:
      sourceDistribution: myDist
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "CN"
        - "GB"

pipelines:
  - name: pipeline_dbppp
    steps:
      - name: docker_build
        type: DockerBuild
        configuration:
          affinityGroup: dbp_group
          dockerFileLocation: .
          dockerFileName: Dockerfile
          dockerImageName: pipelines.westus.cloudapp.azure.com:8082/docker-local/mydockerbase  # replace with your image path and name
          dockerImageTag: '${run_number}'
          inputResources:
            - name: dbp_repo
          integrations:
            - name: zen_art                            # <-- replace with your artifactory integration

      - name: docker_push
        type: DockerPush
        configuration:
          affinityGroup: dbp_group
          targetRepository: docker_local
          integrations:
            - name: zen_art                            # <-- replace with your artifactory integration
          inputSteps:
            - name: docker_build
          outputResources:
            - name: dbp_image

      - name: publish_dbp_build
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: docker_push
          outputResources:
            - name: dbp_build_info

      - name: promote_dbp_build
        type: PromoteBuild
        configuration:
          targetRepository: demo_pipelines
          integrations:
            - name: zen_art
          inputResources:
            - name: dbp_build_info
          outputResources:
            - name: dbp_promoted_build_info

      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo_rb
          releaseBundleVersion: v1.0.${run_number}
          dryRun: false
          sign: false
          description: "some random test description"
          inputResources:
            - name: dbp_build_infooo
              trigger: true
          outputResources:
            - name: release_bundle
          releaseNotes:
            syntax: markdown
            content: |
              ## Heading
                * Bullet
                * Points
